# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes/*.bbappend"

LAYERSERIES_COMPAT_meta-iceoryx2 = "\
    kirkstone \
    scarthgap \
"

# Uncomment to overwrite the preferred iceoryx2 version
#ICEORYX2_VERSION = "git"
